# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Albelli Advertisement Frontend Deploy

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Packages
        run: yarn install
      - name: Run Unit Test
        run: yarn test
      - name: Run Build
        run: yarn build
      - name: Deploy to Dev
        uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          node-version: ${{ matrix.node-version }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "albelli-front" #Must be unique in Heroku
          heroku_email: "sixtus2000gh@yahoo.co.uk"
          
      - name: Deloy to Prod
        # Develop branch only
        if: github.ref == 'refs/heads/main'
        run: |
            echo "Main checks is good but not used at the moment "
    